# Generated by Django 3.1 on 2020-10-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201014_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, choices=[('Pickup', '$0'), ('Standar Delivery', '5'), ('Express Delivery', '12')], decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('Standar Delivery', 'Standar Delivery'), ('Express Delivery', 'Express Delivery')], max_length=120),
        ),
    ]
