# Generated by Django 3.1 on 2020-10-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201019_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='delivery_price',
        ),
    ]
