# Generated by Django 3.1 on 2020-10-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201019_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(blank=True, choices=[('Pickup', '0'), ('Standar Delivery', '5'), ('Express Delivery', '12')], decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
