# Generated by Django 3.1 on 2020-10-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20201019_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(blank=True, choices=[(0, 0), (5, 5), (12, 12)], decimal_places=2, default=1, max_digits=7, null=True),
        ),
    ]
