# Generated by Django 3.1 on 2020-10-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20201019_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(blank=True, choices=[(0.0, 0.0), (5.0, 5.0), (12.0, 12.0)], decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
